# Generated by Django 3.2.25 on 2025-07-13 11:17

import django.core.serializers.json
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_now_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenowgroup',
            name='_custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='servicenowgroup',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicenowgroup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
